### PR TITLE
Support wait before exit

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by zherczeg** [comment]
@clover2123 what do you think of this patch?

**Comment by clover2123** [comment]
This patch looks relavant to `wait_before_exit` implemented in escargot 
https://github.com/Samsung/escargot/blob/2e2b6a83986be8178f9a89ccfefcb2cf6f56371b/src/shell/Shell.cpp#L1046

I want to know how vscode-extension triggers this `wait_before_exit` in spefic
1) initializing vscode-extension with `wait_before_exit` argument
2) when escargot-debugger (remote) is about to quit its run, it sends a message to vscode-extension
3) vscode-extension then re-sends a message to escargot-debugger and waits until escargot-debugger exits

Is the above flow correct?

**Comment by zherczeg** [comment]
1) Yes, currently launch or attach.json must be used to configure this argument.
2) Yes.
3) Basically escargot evaluates an empty string as script, and stops at its first breakpoint (empty string has only one breakpoint). 

Because we are stopped at a breakpoint, vscode shows an empty file, and the user can use the console to evaluate expressions.

Instead of an empty string, we could evaluate a string with a comment, something like this if it is better:
`/* Stopped before exit. Global variables can be checked before the engine terminates. */`

**Comment by clover2123** [comment]
I see :)

> Instead of an empty string, we could evaluate a string with a comment, something like this if it is better:
/* Stopped before exit. Global variables can be checked before the engine terminates. */

This comment looks good! 
Are you going to update this comment part together with this patch ?
Or it should be supported in escargot-debugger?

**Review by clover2123 — APPROVED** [review]

**Comment by zherczeg** [comment]
The script is part of escargot, so yes, it should be updated there, not in this patch.

**Pull request merged**
